### ISSUE TITLE
1) Add the __str__ to the gex object, and 2) add __str__ and plot to the survey object

### ISSUE THREAD

**Issue by burningsage** [emerald-geomodelling/libaarhusxyz#35]
https://github.com/emerald-geomodelling/libaarhusxyz/blob/87a61c5bc9f1c68acb030f14f1c96d11dbf17131/libaarhusxyz/survey.py#L9

**Comment by burningsage** [comment]
Gex: https://github.com/emerald-geomodelling/libaarhusxyz/blob/70646c53faaa1fc3333fb3aa312824e56e275d21/libaarhusxyz/gex.py#L153

Survey: https://github.com/emerald-geomodelling/libaarhusxyz/blob/8cdae238f4ebb6860ea78aeb5482dd671eb4dce1/libaarhusxyz/survey.py#L17

**Comment by redhog** [comment]
Done here: https://github.com/emerald-geomodelling/libaarhusxyz/commit/7f061b1c322af51b8f11d39595e7e27aab0d6a42
