### ISSUE TITLE
libaarhusxyz EM data dump cannot be read by AarhusWorkbench

### ISSUE THREAD

**Issue by mp-emrld** [emerald-geomodelling/libaarhusxyz#7]
Error message:
"Number of columns in data file (149) is smaller than largest column specified in ALC file (151)

Example dataset :
/Emerald Geomodelling/Developments - Documents/DeveloperWorkspaces/TestDatasets/LibaarhusXYZ

see read_write_EMdataAgave_xyz.py for details
20210930_AGAVE_Workbench_XYZ_2Hz.XYZ is the original file

**Comment by mp-emrld** [comment]
Giselle fixed that, needs testing

**Comment by redhog** [comment]
:) :) Do you have a commit id or pr for her fix?

**Comment by glinares-em** [comment]
PR:
https://github.com/emerald-geomodelling/libaarhusxyz/pull/8

**Comment by mp-emrld** [comment]
Just tested the latest fix (branch xyz_dump) and it works for xyz files with a single  header line like in
`/Volumes/GoogleDrive/Shared drives/R_and_D/TestDatasets/LibaarhusXYZ/Exmaple1_oneHeaderLines`

However, it stripes off the header when the original xyz file contains some header lines like in:
`/Volumes/GoogleDrive/Shared drives/R_and_D/TestDatasets/LibaarhusXYZ/Exmaple2_multipleHeaderLines`

see `read_write_xyz.py` for how i tested this

**Comment by mp-emrld** [comment]
This seems to work well for files with a single header line.

However, for xyz files with multiple header lines exported from workbench, one needs to be aware that the number of header lines might change for xyz-files with multiple dipole moments. 
For re-import into workbench, that needs to be reflected in the .ALC file.
