### ISSUE TITLE
Libaarhusxyz: bug parsing  EM data using .ALC files

### ISSUE THREAD

**Issue by mp-emrld** [emerald-geomodelling/libaarhusxyz#9]
the ALC file can contain fields like `["Misc2", "Misc2", "Misc3", "Misc3","Current_Ch01", "Current_Ch02"]`. In that case these fields will be written to dataframes in `data['layer_data']` like `data['layer_data']['Misc']` or `data['layer_data']['Current_Ch']`  but should rather be additional columns of `data['flightlines']`

example to test, including locations of .xyz and .alc files:
 https://github.com/emerald-geomodelling/EmeraldProcessing/blob/libaarhus_data_structure/scripts/TEM/libaarhus_IO_test.py

**Comment by redhog** [comment]
Bugfixed here: https://github.com/emerald-geomodelling/libaarhusxyz/commit/4771c203d26ddf3f338f42749996c4dab777920a
This has been released as version 0.0.5 to pypi
